apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15