kind: Service
apiVersion: v1
metadata:
  name: loadbalancer
  labels:
    app: deploy
spec:
  type: LoadBalancer
  selector:
    deployment: deploy
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP